const fakeData = {
    "page": 1,
    "total_results": 10000,
    "total_pages": 500,
    "results": [{
        "popularity": 83.785,
        "vote_count": 948,
        "video": false,
        "poster_path": "\/p69QzIBbN06aTYqRRiCOY1emNBh.jpg",
        "id": 501170,
        "adult": false,
        "backdrop_path": "\/1nm0sk8UUx9jHCTHuMKe2jkt4Pn.jpg",
        "original_language": "en",
        "original_title": "Doctor Sleep",
        "genre_ids": [18, 14, 27],
        "title": "Doctor Sleep",
        "vote_average": 7.1,
        "overview": "Still irrevocably scarred by the trauma he endured as a child at the Overlook, Dan Torrance has fought to find some semblance of peace. But that peace is shattered when he encounters Abra, a courageous teenager with her own powerful extrasensory gift, known as the 'shine'. Instinctively recognising that Dan shares her power, Abra has sought him out, desperate for his help against the merciless Rose the Hat and her followers.",
        "release_date": "2019-10-30"
    }, {
        "popularity": 33.91,
        "id": 126889,
        "video": false,
        "vote_count": 5428,
        "vote_average": 5.9,
        "title": "Alien: Covenant",
        "release_date": "2017-05-09",
        "original_language": "en",
        "original_title": "Alien: Covenant",
        "genre_ids": [27, 878, 53],
        "backdrop_path": "\/6jajFcaY2YsfGQstJ5HaqZNVseX.jpg",
        "adult": false,
        "overview": "Bound for a remote planet on the far side of the galaxy, the crew of the colony ship 'Covenant' discovers what is thought to be an uncharted paradise, but is actually a dark, dangerous world—which has a sole inhabitant: the 'synthetic', David, survivor of the doomed Prometheus expedition.",
        "poster_path": "\/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg"
    }, {
        "popularity": 52.244,
        "vote_count": 40,
        "video": false,
        "poster_path": "\/mBBBXseq4k4dI63k06XIrsc02j8.jpg",
        "id": 542224,
        "adult": false,
        "backdrop_path": "\/en1XAePgWqNSXb82luUMmo5u3cF.jpg",
        "original_language": "en",
        "original_title": "Gretel & Hansel",
        "genre_ids": [14, 27, 53],
        "title": "Gretel & Hansel",
        "vote_average": 5.4,
        "overview": "A long time ago in a distant fairy tale countryside, a young girl leads her little brother into a dark wood in desperate search of food and work, only to stumble upon a nexus of terrifying evil.",
        "release_date": "2020-01-30"
    }, {
        "popularity": 41.08,
        "vote_count": 7126,
        "video": false,
        "poster_path": "\/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
        "id": 447332,
        "adult": false,
        "backdrop_path": "\/roYyPiQDQKmIKUEhO912693tSja.jpg",
        "original_language": "en",
        "original_title": "A Quiet Place",
        "genre_ids": [18, 27, 878],
        "title": "A Quiet Place",
        "vote_average": 7.3,
        "overview": "A family is forced to live in silence while hiding from creatures that hunt by sound.",
        "release_date": "2018-04-03"
    }, {
        "popularity": 54.476,
        "vote_count": 3090,
        "video": false,
        "poster_path": "\/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
        "id": 474350,
        "adult": false,
        "backdrop_path": "\/8moTOzunF7p40oR5XhlDvJckOSW.jpg",
        "original_language": "en",
        "original_title": "It Chapter Two",
        "genre_ids": [18, 14, 27],
        "title": "It Chapter Two",
        "vote_average": 6.8,
        "overview": "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
        "release_date": "2019-09-04"
    }, {
        "popularity": 44.066,
        "vote_count": 36,
        "video": false,
        "poster_path": "\/uiMHiHp9eAjJty8rddoUnL9G5fU.jpg",
        "id": 492611,
        "adult": false,
        "backdrop_path": "\/yv0NQmX1TWsXmIpxgpDQtlMRixp.jpg",
        "original_language": "en",
        "original_title": "The Turning",
        "genre_ids": [27, 53],
        "title": "The Turning",
        "vote_average": 5.6,
        "overview": "A young governess is hired by a man who has become responsible for his young nephew and niece after the deaths of their parents. A modern take on Henry James' novella \"The Turn of the Screw\".",
        "release_date": "2020-01-23"
    }, {
        "popularity": 34.727,
        "vote_count": 286,
        "video": false,
        "poster_path": "\/qCDPKUMX5xrxxQY8XhGVCKO3fks.jpg",
        "id": 599975,
        "adult": false,
        "backdrop_path": "\/zETkzgle7c6wAeW11snnVUBp67S.jpg",
        "original_language": "en",
        "original_title": "Countdown",
        "genre_ids": [27, 53],
        "title": "Countdown",
        "vote_average": 6.3,
        "overview": "A young nurse downloads an app that tells her she only has three days to live. With time ticking away and a mysterious figure haunting her, she must find a way to save her life before time runs out.",
        "release_date": "2019-10-24"
    }, {
        "popularity": 51.733,
        "vote_count": 1376,
        "video": false,
        "poster_path": "\/dtRbVsUb5O12WWO54SRpiMtHKC0.jpg",
        "id": 338967,
        "adult": false,
        "backdrop_path": "\/3ghImmHdp4RnC3UkL6hpLayclnb.jpg",
        "original_language": "en",
        "original_title": "Zombieland: Double Tap",
        "genre_ids": [28, 35, 27],
        "title": "Zombieland: Double Tap",
        "vote_average": 6.9,
        "overview": "Columbus, Tallahassee, Wichita, and Little Rock move to the American heartland as they face off against evolved zombies, fellow survivors, and the growing pains of the snarky makeshift family.",
        "release_date": "2019-10-09"
    }, {
        "popularity": 48.446,
        "vote_count": 8,
        "video": false,
        "poster_path": "\/ofJp9SfJFlzCaDCUFfvCx08Hwfh.jpg",
        "id": 586592,
        "adult": false,
        "backdrop_path": "\/nIXWrG6xxl56NFBtAR1vlduTEgy.jpg",
        "original_language": "en",
        "original_title": "Come to Daddy",
        "genre_ids": [35, 27, 53],
        "title": "Come to Daddy",
        "vote_average": 6.5,
        "overview": "After receiving a cryptic letter from his estranged father, Norval travels to his dad’s oceanfront home for what he hopes will be a positive experience. If only he’d known the dark truth about his old man beforehand.",
        "release_date": "2020-02-07"
    }, {
        "popularity": 38.512,
        "vote_count": 748,
        "video": false,
        "poster_path": "\/3nk9UoepYmv1G9oP18q6JJCeYwN.jpg",
        "id": 503919,
        "adult": false,
        "backdrop_path": "\/i51wnN9phojyn14xHjQt6rv1r0x.jpg",
        "original_language": "en",
        "original_title": "The Lighthouse",
        "genre_ids": [18, 14, 27, 9648],
        "title": "The Lighthouse",
        "vote_average": 7.7,
        "overview": "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.",
        "release_date": "2019-10-18"
    }, {
        "popularity": 33.825,
        "vote_count": 186,
        "video": false,
        "poster_path": "\/jlHL2BH176JApGiLnNQLQgdjMFd.jpg",
        "id": 443791,
        "adult": false,
        "backdrop_path": "\/fYPiQewg7ogbzro2XcCTACSB2KC.jpg",
        "original_language": "en",
        "original_title": "Underwater",
        "genre_ids": [27, 878, 53],
        "title": "Underwater",
        "vote_average": 6,
        "overview": "After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.",
        "release_date": "2020-01-08"
    }, {
        "popularity": 37.554,
        "vote_count": 1538,
        "video": false,
        "poster_path": "\/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
        "id": 530385,
        "adult": false,
        "backdrop_path": "\/g6GtOfXtzDpY73ef7wludoorTti.jpg",
        "original_language": "en",
        "original_title": "Midsommar",
        "genre_ids": [18, 27, 9648],
        "title": "Midsommar",
        "vote_average": 7.1,
        "overview": "Several friends travel to Sweden to study as anthropologists a summer festival that is held every ninety years in the remote hometown of one of them. What begins as a dream vacation in a place where the sun never sets, gradually turns into a dark nightmare as the mysterious inhabitants invite them to participate in their disturbing festive activities.",
        "release_date": "2019-07-03"
    }, {
        "popularity": 55.152,
        "vote_count": 410,
        "video": false,
        "poster_path": "\/g4z7mDmJmx23vsVg6XNWcnXb6gc.jpg",
        "id": 480105,
        "adult": false,
        "backdrop_path": "\/3uG3aOhEzFCjcQulsJQiAzLSrw8.jpg",
        "original_language": "en",
        "original_title": "47 Meters Down: Uncaged",
        "genre_ids": [27],
        "title": "47 Meters Down: Uncaged",
        "vote_average": 4.9,
        "overview": "Four teenage girls go on a diving adventure to explore a submerged Mayan city. Once inside, their rush of excitement turns into a jolt of terror as they discover the sunken ruins are a hunting ground for deadly great white sharks. With their air supply steadily dwindling, the friends must navigate the underwater labyrinth of claustrophobic caves and eerie tunnels in search of a way out of their watery hell.",
        "release_date": "2019-08-15"
    }, {
        "popularity": 33.573,
        "id": 381283,
        "video": false,
        "vote_count": 4026,
        "vote_average": 7,
        "title": "mother!",
        "release_date": "2017-09-13",
        "original_language": "en",
        "original_title": "mother!",
        "genre_ids": [18, 27, 9648],
        "backdrop_path": "\/uuQpQ8VDOtVL2IO4y2pR58odkS5.jpg",
        "adult": false,
        "overview": "A couple's relationship is tested when uninvited guests arrive at their home, disrupting their tranquil existence.",
        "poster_path": "\/2yOKarmL8B4oXaLXUdHu882SUbu.jpg"
    }, {
        "popularity": 29.602,
        "vote_count": 10062,
        "video": false,
        "poster_path": "\/xazWoLealQwEgqZ89MLZklLZD3k.jpg",
        "id": 694,
        "adult": false,
        "backdrop_path": "\/h4DcDCOkQBENWBJZjNlPv3adQfM.jpg",
        "original_language": "en",
        "original_title": "The Shining",
        "genre_ids": [27, 53],
        "title": "The Shining",
        "vote_average": 8.2,
        "overview": "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
        "release_date": "1980-05-22"
    }, {
        "popularity": 41.09,
        "vote_count": 947,
        "video": false,
        "poster_path": "\/vOl6shtL0wknjaIs6JdKCpcHvg8.jpg",
        "id": 567609,
        "adult": false,
        "backdrop_path": "\/ubqaGfwYxZMaTEVfhPghF87tzYm.jpg",
        "original_language": "en",
        "original_title": "Ready or Not",
        "genre_ids": [35, 27, 9648, 53],
        "title": "Ready or Not",
        "vote_average": 6.8,
        "overview": "A bride's wedding night takes a sinister turn when her eccentric new in-laws force her to take part in a terrifying game.",
        "release_date": "2019-08-21"
    }, {
        "popularity": 26.927,
        "vote_count": 7,
        "video": false,
        "poster_path": "\/tkFZmf2HbONsLaU6OEJ9ebCMQ8R.jpg",
        "id": 608812,
        "adult": false,
        "backdrop_path": "\/5r09qJvWwHnoTJzIWe7mIDfi0kQ.jpg",
        "original_language": "en",
        "original_title": "Handjob Cabin",
        "genre_ids": [35, 27],
        "title": "Handjob Cabin",
        "vote_average": 7,
        "overview": "4 friends descend on a log cabin for a weekend of fun, but an ominious sexually frustrated presence resides within.  Short trailers for a fictious movie...",
        "release_date": "2015-10-06"
    }, {
        "popularity": 10.754,
        "vote_count": 0,
        "video": false,
        "poster_path": "\/lRT4lbEUb4g0Yhi19iAJvxahiiH.jpg",
        "id": 664561,
        "adult": false,
        "backdrop_path": "\/1hZRRbtzQ7swNm0kdRxJTEX1ajY.jpg",
        "original_language": "en",
        "original_title": "Cruel Peter",
        "genre_ids": [27],
        "title": "Cruel Peter",
        "vote_average": 0,
        "overview": "It is Christmas 1908 in Messina, one of the richest merchant cities of the Mediterranean. Peter, the 13 year-old son of a rich English family is notorious for his cruelty to children, animals and servants. One night he is ambushed and wakes up in a coffin underground in the city's Gothic cemetery, buried in retaliation for his callousness by a servant boy from his mother's estate. When a powerful earthquake razes Messina to the ground, Peter is trapped and his whereabouts are forgotten. Until a century later an English archaeologist and his daughter arrive in the city.",
        "release_date": "2020-02-06"
    }, {
        "popularity": 19.893,
        "vote_count": 3851,
        "video": false,
        "poster_path": "\/cTaEIUYTt52ooq9quVbAQ7NpGwo.jpg",
        "id": 440021,
        "adult": false,
        "backdrop_path": "\/9bjHAkyi3aRRnfrIGhHPu7RATPR.jpg",
        "original_language": "en",
        "original_title": "Happy Death Day",
        "genre_ids": [27, 9648, 53],
        "title": "Happy Death Day",
        "vote_average": 6.6,
        "overview": "Caught in a bizarre and terrifying time warp, college student Tree finds herself repeatedly reliving the day of her murder, ultimately realizing that she must identify the killer and the reason for her death before her chances of survival run out.",
        "release_date": "2017-10-12"
    }, {
        "popularity": 25.922,
        "vote_count": 1588,
        "video": false,
        "poster_path": "\/fWOPN0XBvHXFYr3RsPr74qBge2I.jpg",
        "id": 243688,
        "adult": false,
        "backdrop_path": "\/i2otKlu6k5xM0bvA69y4z7XaCGo.jpg",
        "original_language": "en",
        "original_title": "Poltergeist",
        "genre_ids": [27, 53],
        "title": "Poltergeist",
        "vote_average": 5.1,
        "overview": "Legendary filmmaker Sam Raimi and director Gil Kenan reimagine and contemporize the classic tale about a family whose suburban home is invaded by angry spirits. When the terrifying apparitions escalate their attacks and take the youngest daughter, the family must come together to rescue her.",
        "release_date": "2015-05-20"
    }]
}

module.exports = fakeData;